name: Secrets Scan in the Repo
on:
  workflow_dispatch: {}
  workflow_call:
    inputs:
      branch:
        description: 'Name of the branch - to checkout code. By default, checkout will be from main branch'
        required: false
        type: string
        default: 'main'
      trigger-secrets-scan:
        description: 'Enable / Disable Secrets Scanning'
        required: false
        type: boolean
        default: true

jobs:
  secrets-scan:
    name: Run Secrets Scan using Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - name: Download and Install Gitleaks binary
        run: |
          GITLEAKS_VERSION=8.18.4
          wget https://github.com/gitleaks/gitleaks/releases/download/v$GITLEAKS_VERSION/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz -O gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz gitleaks
          mv gitleaks /usr/local/bin/gitleaks
          chmod +x /usr/local/bin/gitleaks

      - name: Run Gitleaks
        continue-on-error: true
        run: |
          echo "Gitleaks version being Used:"
          gitleaks version
          echo "Starting Gitleaks scan..."
          gitleaks detect --log-opts="--pretty --all" --verbose --redact=50 --report-path gitleaks-report.json | tee gitleaks-report.txt

      - name: Publish Gitleaks Output to Summary
        if: always()
        run: |
          if [[ -s gitleaks-report.txt ]]; then
          {
            echo "### Security Output"
            echo "<details><summary>Click to expand Secrets scanning results</summary>"
            echo ""
            echo '```secrets-scan'
            cat gitleaks-report.txt
            echo '```'
            echo "</details>"
          } >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload Gitleaks report as build artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: |
                gitleaks-report.json
                gitleaks-report.txt

  deploy:
    name: Deploy secrets-scan results
    runs-on: ubuntu-latest
    needs: secrets-scan
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Download build artifact
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: gitleaks-report
          path: .

      - name: Configure GH Pages
        if: always()
        uses: actions/configure-pages@v3

      - name: Upload Gitleaks report as GH Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
      
      - name: Deploy Gitleaks results to GitHub Pages
        uses: actions/deploy-pages@v4
